TestTask/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace='items')),
]

items/urls.py
from django.urls import path

from items import views

app_name = 'items'

urlpatterns = [
    path('items/', views.ItemsListView.as_view(), name='items'),
    path('item/<int:item_id>/', views.ItemShowView.as_view(), name='item'),
    path('buy/<int:item_id>/', views.buyitem, name='buying'),
]

items/models.py
from django.db import models

# Create your models here.


class Items(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)

    class Meta:
        db_table = 'item'
        verbose_name = 'Вещь'
        verbose_name_plural = 'Вещи'

    def __str__(self):
        return f'{self.name}'

items/views.py
import stripe
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, FormView, TemplateView
from TestTask import settings
from items.models import Items

# Create your views here.


class ItemShowView(DetailView):
    model = Items
    template_name = 'items/itemshow.html'
    context_object_name = 'item'

    def get(self, request, item_id) -> HttpResponse:
        item = Items.objects.get(id=item_id)
        return render(self.request, 'items/itemshow.html', {'item': item})

class ItemsListView(ListView):
    model = Items
    template_name = 'items/index.html'
    paginate_by = 3
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    
def buyitem(request, item_id):
    item = Items.objects.get(id=item_id)
    item_price = str(item.price)
    item_price = item_price.replace('.', '')
    item_price = int(item_price)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    intent = stripe.PaymentIntent.create(
        amount=item_price,
        currency='usd',
        metadata= {'userid': request.user.id}
    )
    return render(request, 'items/itembuying.html', {'item': item, 'client_secret': intent.client_secret, 
                                                        'STRIPE_PUBLISHABLE_KEY': settings.STRIPE_PUBLISHABLE_KEY})

items/templates/items/index.html
{% extends "items/layout.html" %}


    {% block head %}
        <title>Все товары</title>
    {% endblock head %}
    {% block content %}
    {% for item in items %}
        <div class='col-lg-4 col-md-6 mt-4'>
            <div class='card'>
                <ul>
                    <li><a href='{% url "items:item" item.id %}'>{{item.name}}</a><p>{{item.price}}$</p></li>
                </ul>
            </div>
        </div>
    {% endfor %}
    
    {% endblock content %}

items/templates/items/itembuying.html
{% extends "items/layout.html" %}
{% load static %}

{% block head %}
<title>Купить {{item.name}}</title>
<link rel="stylesheet" href="{% static 'items/css/payment.css' %}">
{% endblock head %}

{% block content %}
<form id="payment-form">
  <h3 class="mb-3">Billing address</h3>
  <!-- Error messages in this element -->
  <div id="card-errors" class="a" role="alert"></div>
  <div class="row g-3">
    <div class="col-sm-7">
      <label for="firstName" class="form-label">Cardholder</label>
      <input type="text" class="form-control" id="custName" placeholder="" required>
      <div class="invalid-feedback">
        Valid first name is required.
      </div>
    </div>
    <div class="col-12">
      <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
      <input type="email" class="form-control" id="email" placeholder="you@example.com">
      <div class="invalid-feedback">
        Please enter a valid email address for shipping updates.
      </div>
    </div>
    <div class="col-12">
      <label for="address" class="form-label">Address</label>
      <input type="text" class="form-control" id="custAdd" placeholder="1234 Main St" required>
      <div class="invalid-feedback">
        Please enter your shipping address.
      </div>
    </div>
    <div class="col-md-5">
      <label for="country" class="form-label">Country</label>
      <select class="form-select" id="country" required>
        <option value="">Choose...</option>
        <option>United States</option>
        <option>Russia</option>
      </select>
      <div class="invalid-feedback">
        Please select a valid country.
      </div>
    </div>

  </div>
  <hr class="my-4">
  <h4 class="mb-3">Payment</h4>
  <label for="card-element">Credit or debit card</label>
  <div id="card-element" class="form-control form-control-payment">
    <!-- Payment elements will appear here -->
  </div>
  <hr class="my-4">
  <button id="submit" class="btn btn-primary w-100 fw-bold" data-secret="{{ client_secret }}">Pay</button>
</form>

<script>
  var STRIPE_PUBLISHABLE_KEY = '{{STRIPE_PUBLISHABLE_KEY}}'
  var CSRF_TOKEN = '{{ csrf_token }}';
</script>
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'items/js/index.js' %}" data-rel-js></script>
{% endblock content %}

items/templates/items/itemshow.html
{% extends "items/layout.html" %}

{% block head %}
    <title>{{item.name}}</title>
{% endblock head %}


{% block content %}
    <div id='item-info'>
        <div>
            {{item.name}}
            {{item.description}}
            {{item.price}}$
        </div>
        <p><a id='buying' href='{% url "items:buying" item.id %}'><button>Buy</button></a></p>
    </div>

{% endblock content %}

items/templates/items/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href='{% static "items/css/styles.css" %}' rel='stylesheet'>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    {% block head %}
    
    {% endblock head %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark-subtle custom-shadow">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Stripe</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Administration</a>
                </div>
              </div>
            </div>
          </nav>
    </header>
    <section>
        <div class="left-chapter">

        </div>
        <div class="content">
            {% block content %}
            {%endblock content%}
        </div>
        <div class="right-chapter">

        </div>
    </section>
    <footer>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>